services:
  - name: prometheus
    image: prom/prometheus
    ports:
      - "9093:9090"
    volumes:
      - "./monitoring/prometheus/:/etc/prometheus/"
      - "./monitoring/prometheus/data:/data"
  - name: malwaretotal
    image: explabs/malwaretotal
    ports:
      - "9092:8000"
    volumes:
      - "./configs/malware.json:/app/malware.json"

